### ISSUE TITLE
Turning off onion skin crashed sprite

### ISSUE THREAD

**Issue by Bradx** [fengeon/Resprite-doc#102]
Experienced an issue where I had a basic sprite.  Added 4 custom frames, then copied and pasted the frames to extend a simple animation.  I turned off Onion skin.  Then went to undo a recent edit. The sprite disappeared back to Resprite’s main screen.  

On re-opening the sprite, all the frames had reverted back to the original.

**Comment by fengeon** [comment]
Can not reproduce the crash
