### ISSUE TITLE
Unable to import

### ISSUE THREAD

**Issue by CapybaraAruMao** [fengeon/Resprite-doc#122]
Hello! I try to import aseprite archive to resprite
He cannot be selected in my drive
Even the files I exported cannot be imported again
do you know what the problem is? i just bought lifetime payment on ipad
I use google drive

**Comment by CapybaraAruMao** [comment]
By the way, I use icloud and it works.

**Comment by fengeon** [comment]
It's google drive's problem. Try save the file to local, then import from local files.
