### ISSUE TITLE
Theme color becoming grey when back

### ISSUE THREAD

**Issue by VADERtheSAIYAN** [fengeon/Resprite-doc#45]
After last update app became a lot more laggy, I had crushes without saving of progression. Also still have problem with appearance theme which somehow becoming grey every time I’m coming back to app. Aand I found some tools working incorrect with Apple Pencil. Sometimes it happens even with pencil tool. Everything I do goes one pixel up from the place I’m actually put pencil at. 
P.S. tested on iPad Pro 9,7.

**Comment by fengeon** [comment]
Looks like weird behavior, I'll look into it.

**Comment by fengeon** [comment]
Seems hard to reproduce, let me know if you have further information

**Comment by fengeon** [comment]
It cannot be reproduced after a period of time.
