### ISSUE TITLE
Pixels are shifted up when painting

### ISSUE THREAD

**Issue by kikoosvk** [fengeon/Resprite-doc#55]
Hello,

I am using the pencil tool, but the pixels are not being painted if I am coming from the top of the particular pixel. The more zoomed out I am, the more prevalent the issue is.
It is the opposite if I make a line from the bottom to the top, then the pencil does not need to even touch the pixel to be painted.
It's like the pixels are shifted. [Here is a short video demonstration.](https://www.youtube.com/shorts/B3PhBfwYDOQ) Thank you all for any kind of help.

![The pixel not being painted.](https://i.imgur.com/JBUvVke.png)

**Comment by fengeon** [comment]
It seems that the calculated position is on the upper side. Please tell me the model of your device.

Do you have "hide system status bar" turned on? If yes, you can turn it off first and that should fix the issue. (Please let us know if this is the reason).

**Comment by kikoosvk** [comment]
Hi, the iPad model is Apple iPad 9.7 (2018) and yes, if I check the Hide system status bar checkbox, the issue disappears. Thanks

**Comment by fengeon** [comment]
fix with 1.9
