### ISSUE TITLE
Increase duration time 

### ISSUE THREAD

**Issue by VADERtheSAIYAN** [fengeon/Resprite-doc#59]
I found that pretty often I need set duration more than accessible 5x. At least to 10x. 

Also would be great to have an option to set preferences for each frame layer, not only for whole frame column

**Comment by fengeon** [comment]
ok, will changed to 10x as max value.

"Also would be great to have an option to set preferences for each frame layer, not only for whole frame column"：
I probably understand your needs, you may want to stagger the duration of the two layers. For example:

Layer 1:ABBBBBCD
Layer 2:AABBBBCD

I currently feel that very few people need it, so it won't be implemented.

**Comment by fengeon** [comment]
op in r10
