### ISSUE TITLE
Provide scripts for convert .ase to .resprite file

### ISSUE THREAD

**Issue by aceimnorstuvwxz** [fengeon/Resprite-doc#66]
I think make a script to convert is more simple than implement in the iOS env, and has the same result.

**Comment by aceimnorstuvwxz** [comment]
So i can import my sprites into the app and keeps the layers

**Comment by fengeon** [comment]
already support .aseprite file import/export in r17.
so the scripts desc here are not needed

**Comment by GieziJo** [comment]
I'm on android, and I was looking into using resprite on my tablet but would like to continue using aseprite on my pc, but can't find the export/inport option for aseprite files.

Will this option be added in the future?

Thanks

**Comment by aceimnorstuvwxz** [comment]
> I'm on android, and I was looking into using resprite on my tablet but would like to continue using aseprite on my pc, but can't find the export/inport option for aseprite files.
> 
> Will this option be added in the future?
> 
> Thanks

YES, on plan
