### ISSUE TITLE
The reference image 90degrees problem

### ISSUE THREAD

**Issue by mjs34** [fengeon/Resprite-doc#68]
Consider adding the ability to rotate and resize  imported reference images. A couple times now my imported image has been rotated 90 degrees and there's no way to fix.

Otherwise, I'm really excited about this app. I was surprised by the lack of a high quality pixel art app on the app store and this seems to have the potential to fill that gap. I hope you continue develop it to it's full potential. The price is right for now too. It's nice to be able to subscribe for a low financial commitment while I evaluate the app.

**Comment by fengeon** [comment]
Known issue is that when the image source is taken by a camera, it will incorrectly be rotated 90 degrees.
Zoom, you can change it by dragging the "<100%>" position, or double-click the picture.

Two-finger zooming will be available in the future.

**Comment by mjs34** [comment]
Got it. It was an image from my camera. I was able to fix by running a resize image shortcut on my iphone. I assumed the size was the issue, but it sounds like just re-saving the image would have worked as well.

Thanks for the reply.
