### ISSUE TITLE
Can show size and position of selection in a near floating panel

### ISSUE THREAD

**Issue by fengeon** [fengeon/Resprite-doc#74]

**Comment by aceimnorstuvwxz** [comment]
https://github.com/fengeon/Resprite-doc/discussions/72#:~:text=Add%20the%20option%20to%20show%20size%20/%20coordinates%20next%20to%20marquee%20selection%20tool%20%2D%20To%20improve%20visibility%20of%20this%20information%20if%20needed.

**Comment by aceimnorstuvwxz** [comment]
![image](https://github.com/fengeon/Resprite-doc/assets/7871447/78fda243-5b5c-46d5-b297-f46136b62290)

**Comment by aceimnorstuvwxz** [comment]
comming with  r29
