### ISSUE TITLE
Misspelled word "pelette" and inconsistency in the terms used or tools naming

### ISSUE THREAD

**Issue by Kormann** [fengeon/Resprite-doc#97]
Misspelled word "pelette" instead of palette were found here:

<img width="552" alt="image" src="https://github.com/fengeon/Resprite-doc/assets/94715325/c1b1288f-6ed0-4336-9fb1-8092a0096b6e">

And here:
<img width="554" alt="image" src="https://github.com/fengeon/Resprite-doc/assets/94715325/19b6b7a3-5eaf-4965-95de-a873cb67bb1c">

I found another inconsistency here:
<img width="630" alt="image" src="https://github.com/fengeon/Resprite-doc/assets/94715325/e5c9e29b-cbb7-4479-8b82-148fd5bdccda">

ColorPicker written as in the panel or Color Picker as in preferences?

<img width="563" alt="image" src="https://github.com/fengeon/Resprite-doc/assets/94715325/76a6aa1a-eaf6-420f-9ae2-c6eb4ffdd0f3">

OnionSkin or onion-skin ?

<img width="549" alt="image" src="https://github.com/fengeon/Resprite-doc/assets/94715325/c2e033a0-9c8f-4cdc-9cbc-d3331103db93">

ToolBar or Toolbar?

This is what I found, maybe there are more naming inconsistencies.

Keep the good work!

**Comment by fengeon** [comment]
thanks, fix in next version!

**Comment by sujoybyte** [comment]
Another one I wanted to tell for a while is the "Canvas preset sizes" it will look nice and perfect as "Canvas Preset Sizes" or "Canvas Presets" (as I think size wording clearly denotes canvas sizes) so it follows other naming conventions.
