### ISSUE TITLE
Label on foot or on cursor show height and width of the form

### ISSUE THREAD

**Issue by raulleite** [fengeon/Resprite-doc#99]
Feature to show the size of the form (square, circle, etc..) when I create one of that.

![image](https://github.com/fengeon/Resprite-doc/assets/18625177/ca6cd84e-8fa4-465e-b365-bf884e5dc4c1)

**Comment by raulleite** [comment]
I guess this request is duplicated, but will be great something like that

**Comment by aceimnorstuvwxz** [comment]
yes, thanks. this will be added soon

**Comment by aceimnorstuvwxz** [comment]
comming in r29
